# name: Pull request to main branch

# on:
#   pull_request:

# jobs:
#   run-tests:
#     strategy:
#       matrix:
#         python-version: ['3.11']
#         os: [ubuntu-latest]
#       fail-fast: false
#     runs-on: ${{ matrix.os }}
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Set up Python ${{ matrix.python-version }}
#         uses: actions/setup-python@v4
#         with:
#           python-version: ${{ matrix.python-version }}

#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           python -m pip install '.[tests]'

#       - name: Test with pytest
#         run: |
#           pytest
#   build-docs:
#     strategy:
#       matrix:
#         python-version: ['3.11']
#         os: [ubuntu-latest]
#       fail-fast: false
#     runs-on: ${{ matrix.os }}
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Set up Python ${{ matrix.python-version }}
#         uses: actions/setup-python@v4
#         with:
#           python-version: ${{ matrix.python-version }}
#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           python -m pip install --editable '.[docs]'
#       - name: Build documentation
#         run: |
#           mkdocs build
#   check_pre-commit:
#     strategy:
#       matrix:
#         python-version: ['3.11']
#         os: [ubuntu-latest]
#       fail-fast: false
#     runs-on: ${{ matrix.os }}
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Set up Python ${{ matrix.python-version }}
#         uses: actions/setup-python@v4
#         with:
#           python-version: ${{ matrix.python-version }}
#       - name: Install pre-commit
#         run: |
#           python -m pip install --upgrade pip
#           python -m pip install '.[dev]'

#       - name: Run pre-commit checks
#         run: |
#           pre-commit run --all-files
